version: 2.1

jobs:
  test:
    docker:
      - image: dart:2.16.1
    parallelism: 2
    steps:
      - checkout
      - run:
          name: Download dependencies
          command: pub get
      - run:
          name: Test
          command: dart run test --file-reporter json:test_results/tests_report.json --reporter expanded
      - store_test_results:
          path: test_results/
      - store_artifacts:
          path: test_results/

workflows:
  version: 2
  build:
    jobs:
      - test