version: 2.1

jobs:
  test:
    docker:
      - image: dart:2.16.1
    steps:
      - checkout
      - run:
          name: Download dependencies
          command: pub get
      - run:
          name: Test
          command: pub run test

workflows:
  version: 2
  build:
    jobs:
      - test